.PHONY: help venv install migrate migration downgrade dev-backend dev-frontend up down clean

PYTHON ?= python3
VENV   := .venv
PIP    := $(VENV)/bin/pip
ALEMBIC := cd backend && ../$(VENV)/bin/alembic

help:
	@echo "Available targets:"
	@echo "  venv          Create Python virtualenv at $(VENV)"
	@echo "  install       Install backend Python deps into $(VENV)"
	@echo "  migrate       Apply all pending Alembic migrations (alembic upgrade head)"
	@echo "  migration m=\"msg\"  Generate a new autogenerated migration"
	@echo "  downgrade     Roll back one migration step"
	@echo "  dev-backend   Run FastAPI with --reload on :8000"
	@echo "  dev-frontend  Run Next.js dev server on :3000"
	@echo "  up            docker compose up --build"
	@echo "  down          docker compose down"
	@echo "  clean         Remove __pycache__ and local sqlite DB"

venv:
	$(PYTHON) -m venv $(VENV)
	$(PIP) install --upgrade pip

install: venv
	$(PIP) install -r backend/requirements.txt

migrate:
	$(ALEMBIC) upgrade head

migration:
	@if [ -z "$(m)" ]; then echo "Usage: make migration m=\"description\""; exit 1; fi
	$(ALEMBIC) revision --autogenerate -m "$(m)"

downgrade:
	$(ALEMBIC) downgrade -1

dev-backend:
	cd backend && ../$(VENV)/bin/uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

dev-frontend:
	cd frontend && npm run dev

up:
	docker compose up --build

down:
	docker compose down

clean:
	find . -type d -name __pycache__ -prune -exec rm -rf {} +
	rm -f backend/aladdinai.db
