# Exported from Render on 2026-05-31T04:27:03Z
version: "1"
services:
- type: web
  name: AladdinAI
  runtime: docker
  repo: https://github.com/aliyevaladddin/AladdinAI
  plan: free
  envVars:
  - key: FERNET_KEY
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  dockerContext: .
  dockerfilePath: ./Dockerfile
  registryCredential:
    fromRegistryCreds:
      name: mycredential
  autoDeployTrigger: commit
  rootDir: backend
  previews:
    generation: manual
