# NOTICE: This file is protected under RCF-PL
"""Text-to-image generation with a pluggable backend.

Backend selection via env, so a dead upstream never requires a code change
(the hosted NIM FLUX.1-schnell endpoint this module originally targeted
stopped answering requests — verified 2026-08-16, connections just hang):

- ``IMAGE_GEN_BACKEND``: ``openai`` (default) | ``dashscope``
- ``IMAGE_GEN_URL``: submit URL (per-backend defaults below)
- ``IMAGE_GEN_MODEL``: model name; OpenAI-compatible gateways want it in body
- ``IMAGE_GEN_API_KEY``: overrides the agent's provider key, so images can be
  generated by a different vendor than the calling agent's chat LLM

Without ``IMAGE_GEN_API_KEY`` the calling agent's own provider key is reused
(``app.crypto.decrypt`` exactly like ``llm_service``), never a second key path.

``generate_image_bytes`` returns raw image bytes + mime; callers persist them
with ``media_service.save_bytes`` and hand them back as outgoing attachments,
the same contract ``send_image`` uses.
"""
from __future__ import annotations

import asyncio
import base64
import logging
import os
from urllib.parse import urlsplit

import httpx

from app.crypto import decrypt
from app.models.llm_provider import LLMProvider
from app.services.llm_service import LLMError

log = logging.getLogger(__name__)

# Hosted NIM FLUX.1-schnell — historical default for the openai path. The
# hosted pool stopped responding (verified 2026-08-16); point IMAGE_GEN_URL /
# IMAGE_GEN_BACKEND at a live gateway instead of relying on this.
DEFAULT_IMAGE_GEN_URL = (
    "https://ai.api.nvidia.com/v1/genai/black-forest-labs/flux.1-schnell"
)
DEFAULT_STEPS = 4  # FLUX.1-schnell is distilled for very few steps
DEFAULT_TIMEOUT = 60.0  # fail fast: a working image backend answers in seconds

# DashScope (Alibaba Model Studio) native text2image API — async contract:
# submit returns a task_id, poll /api/v1/tasks/<id> until SUCCEEDED, then
# download the image from output.results[0].url.
DEFAULT_DASHSCOPE_URL = (
    "https://dashscope-intl.aliyuncs.com"
    "/api/v1/services/aigc/text2image/image-synthesis"
)
DEFAULT_DASHSCOPE_MODEL = "wan2.2-t2i-flash"
DASHSCOPE_POLL_INTERVAL = 2.0


# [RCF:PROTECTED]
def _decode_image(data: dict) -> bytes:
    """Pull base64 image bytes out of either the native NIM `artifacts`
    response or the OpenAI-compatible `data[...].b64_json` response."""
    # Native NIM genai: {"artifacts": [{"base64": "..."}]}
    artifacts = data.get("artifacts")
    if isinstance(artifacts, list) and artifacts:
        b64 = artifacts[0].get("base64")
        if b64:
            return base64.b64decode(b64)
    # OpenAI-compatible /v1/images/generations: {"data": [{"b64_json": "..."}]}
    items = data.get("data")
    if isinstance(items, list) and items:
        b64 = items[0].get("b64_json")
        if b64:
            return base64.b64decode(b64)
    raise LLMError(f"No image in response: {str(data)[:200]}")


# [RCF:PROTECTED]
def _sniff_mime(img: bytes) -> str:
    """Detect image mime from magic bytes — backends may return PNG or JPEG."""
    if img[:8] == b"\x89PNG\r\n\x1a\n":
        return "image/png"
    if img[:3] == b"\xff\xd8\xff":
        return "image/jpeg"
    if img[:4] == b"RIFF" and img[8:12] == b"WEBP":
        return "image/webp"
    return "image/png"  # sensible default; save_bytes maps it to .png


# [RCF:PROTECTED]
async def _generate_dashscope(
    url: str,
    api_key: str | None,
    model: str,
    prompt: str,
    timeout: float,
) -> tuple[bytes, str]:
    """DashScope text2image: submit task -> poll status -> download image URL."""
    headers = {"Accept": "application/json", "Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"
    headers["X-DashScope-Async"] = "enable"

    payload = {
        "model": model,
        "input": {"prompt": prompt},
        "parameters": {"size": "1024*1024", "n": 1},
    }
    parts = urlsplit(url)
    task_base = f"{parts.scheme}://{parts.netloc}"

    async with httpx.AsyncClient(timeout=30.0) as client:
        for attempt in range(2):
            try:
                resp = await client.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                break
            except httpx.ConnectError as e:
                # Codespaces DNS is flaky (EAI_AGAIN); one immediate retry.
                if attempt == 1:
                    raise LLMError(
                        f"DashScope submit {type(e).__name__}: {str(e) or 'no details'}"
                    ) from e
                log.warning("DashScope submit connect failed (%s); retrying once", e)
                await asyncio.sleep(1.0)
            except httpx.TimeoutException as e:
                raise LLMError(
                    f"DashScope submit did not respond ({type(e).__name__}, url={url})"
                ) from e
            except httpx.HTTPStatusError as e:
                raise LLMError(
                    f"DashScope submit HTTP {e.response.status_code}: {e.response.text[:300]}"
                ) from e
            except httpx.HTTPError as e:
                raise LLMError(
                    f"DashScope submit {type(e).__name__}: {str(e) or 'no details'}"
                ) from e

        try:
            task_id = (resp.json().get("output") or {}).get("task_id")
        except ValueError as e:
            raise LLMError(f"DashScope submit returned non-JSON: {resp.text[:200]}") from e
        if not task_id:
            raise LLMError(f"DashScope returned no task_id: {resp.text[:200]}")

        poll_headers = {"Accept": "application/json"}
        if api_key:
            poll_headers["Authorization"] = f"Bearer {api_key}"
        task_url = f"{task_base}/api/v1/tasks/{task_id}"
        deadline = asyncio.get_running_loop().time() + timeout
        status = "PENDING"
        while True:
            await asyncio.sleep(DASHSCOPE_POLL_INTERVAL)
            if asyncio.get_running_loop().time() > deadline:
                raise LLMError(f"DashScope task {task_id} still {status} after {timeout:.0f}s")
            try:
                t = await client.get(task_url, headers=poll_headers)
                t.raise_for_status()
                out = t.json().get("output") or {}
            except (httpx.HTTPError, ValueError) as e:
                # Transient poll hiccup — keep polling until the deadline.
                log.warning("DashScope poll hiccup for task %s: %r", task_id, e)
                continue
            status = out.get("task_status", status)
            if status == "SUCCEEDED":
                results = out.get("results") or []
                img_url = results[0].get("url") if results else None
                if not img_url:
                    raise LLMError(
                        f"DashScope task succeeded without an image url: {str(out)[:200]}"
                    )
                try:
                    img = (await client.get(img_url)).content
                except httpx.HTTPError as e:
                    raise LLMError(
                        f"DashScope image download failed: {type(e).__name__}: "
                        f"{str(e) or 'no details'}"
                    ) from e
                if not img:
                    raise LLMError("DashScope image download returned empty body")
                return img, _sniff_mime(img)
            if status in ("FAILED", "UNKNOWN"):
                raise LLMError(f"DashScope task {status}: {str(out)[:300]}")


# [RCF:PROTECTED]
async def generate_image_bytes(
    provider: LLMProvider,
    prompt: str,
    *,
    steps: int | None = None,
    seed: int = 0,
    timeout: float = DEFAULT_TIMEOUT,
) -> tuple[bytes, str]:
    """Generate an image from `prompt`. Returns (image_bytes, mime).

    Raises LLMError on any upstream/decoding failure.
    """
    prompt = (prompt or "").strip()
    if not prompt:
        raise LLMError("Empty image prompt")

# [RCF:PROTECTED]
    api_key = os.environ.get("IMAGE_GEN_API_KEY") or (
        decrypt(provider.api_key_encrypted) if provider.api_key_encrypted else None
    )

    backend = os.environ.get("IMAGE_GEN_BACKEND", "openai").strip().lower()
    if backend == "dashscope":
        url = os.environ.get("IMAGE_GEN_URL", DEFAULT_DASHSCOPE_URL)
        model = os.environ.get("IMAGE_GEN_MODEL", DEFAULT_DASHSCOPE_MODEL)
        return await _generate_dashscope(url, api_key, model, prompt, timeout)

    # Default path: one-shot OpenAI-compatible (or NIM genai) POST.
    url = os.environ.get("IMAGE_GEN_URL", DEFAULT_IMAGE_GEN_URL)

    headers = {"Accept": "application/json", "Content-Type": "application/json"}
    if api_key:
        headers["Authorization"] = f"Bearer {api_key}"

    payload: dict = {
        "prompt": prompt,
        "steps": steps if steps is not None else DEFAULT_STEPS,
        "seed": seed,
    }
    # Optional model override (OpenAI-compatible gateways want it in the body).
    model = os.environ.get("IMAGE_GEN_MODEL")
    if model:
        payload["model"] = model
        payload["response_format"] = "b64_json"

    async with httpx.AsyncClient(timeout=timeout) as client:
        for attempt in range(2):
            try:
                resp = await client.post(url, json=payload, headers=headers)
                resp.raise_for_status()
                break
            except httpx.ConnectError as e:
                # Transient DNS/network glitches (EAI_AGAIN in Codespaces) are
                # worth one immediate retry; real timeouts are not retried.
                if attempt == 1:
                    raise LLMError(f"{type(e).__name__}: {str(e) or 'no details'}") from e
                log.warning("image generation connect failed (%s); retrying once", e)
                await asyncio.sleep(1.0)
            except httpx.TimeoutException as e:
                raise LLMError(
                    f"Image endpoint did not respond within {timeout:.0f}s "
                    f"({type(e).__name__}, url={url})"
                ) from e
            except httpx.HTTPStatusError as e:
                raise LLMError(f"HTTP {e.response.status_code}: {e.response.text[:300]}") from e
            except httpx.HTTPError as e:
                raise LLMError(f"{type(e).__name__}: {str(e) or 'no details'}") from e

    try:
        data = resp.json()
    except ValueError as e:
        raise LLMError(f"Image endpoint returned non-JSON: {resp.text[:200]}") from e

    img_bytes = _decode_image(data)
    return img_bytes, _sniff_mime(img_bytes)
