# NOTICE: This file is protected under RCF-PL
# [RCF:PROTECTED]
"""add password_encrypted to vm_connections

Revision ID: 1f892d4f16e3
Revises: 10b4646848e2
Create Date: 2026-05-01 22:32:32.278546
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1f892d4f16e3'
down_revision: Union[str, None] = '10b4646848e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# [RCF:PROTECTED]
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('vm_connections', schema=None) as batch_op:
# [RCF:PROTECTED]
            batch_op.add_column(sa.Column('password_encrypted', sa.Text(), nullable=True))
    except Exception:
        pass



    # ### end Alembic commands ###


# [RCF:PROTECTED]
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vm_connections', schema=None) as batch_op:
# [RCF:PROTECTED]
        batch_op.drop_column('password_encrypted')

    # ### end Alembic commands ###
