# NOTICE: This file is protected under RCF-PL
"""add agent_id to activities

Revision ID: 4d80430a55ae
Revises: 3b8c2e1a9f7d
Create Date: 2026-05-08 10:56:37.340326
"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

revision: str = '4d80430a55ae'
down_revision: str | None = '3b8c2e1a9f7d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# [RCF:PROTECTED]
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_activities_agent_id', 'agents', ['agent_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


# [RCF:PROTECTED]
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_constraint('fk_activities_agent_id', type_='foreignkey')
        batch_op.drop_column('agent_id')

    # ### end Alembic commands ###
