# NOTICE: This file is protected under RCF-PL
"""make_contact_id_nullable

Revision ID: 66adfe6c7cf3
Revises: 4d80430a55ae
Create Date: 2026-05-08 14:14:20.259445
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66adfe6c7cf3'
down_revision: Union[str, None] = '4d80430a55ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# [RCF:PROTECTED]
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_messages_parent_session')
        batch_op.drop_index('ix_agent_messages_to_agent_status')

    with op.batch_alter_table('agent_triggers', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_triggers_user_enabled')

    # ### end Alembic commands ###


# [RCF:PROTECTED]
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_triggers', schema=None) as batch_op:
        batch_op.create_index('ix_agent_triggers_user_enabled', ['user_id', 'enabled'], unique=False)

    with op.batch_alter_table('agent_messages', schema=None) as batch_op:
        batch_op.create_index('ix_agent_messages_to_agent_status', ['to_agent_id', 'status'], unique=False)
        batch_op.create_index('ix_agent_messages_parent_session', ['parent_session_id'], unique=False)

    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.alter_column('contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
